import test from "ava";
import { StringContentEntry } from "content-entry";
import { createContext, asyncIterator2scalar } from "./helpers/util.mjs";
import { YARNLockfile } from "../src/mergers/yarn-lockfile.mjs";

const content = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.10.4":
  version "7.10.4"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz#168da1a36e90da68ae8d49c0f1b48c7c6249213a"
  integrity sha512-vG6SvB6oYEhvgisZNFRmRCUkLz11c7rp+tbNTynGqc6mS1d5ATd/sGyV6W0KZZnXRKMTzZDRgQT3Ou9jhpAfUg==
  dependencies:
    "@babel/highlight" "^7.10.4"
`;

test("yarn lockfile merge", async t => {
  const commit = await asyncIterator2scalar(
    YARNLockfile.commits(
      await createContext({
        description: "the description"
      }),
      new StringContentEntry("yarn.lock", content),
      new StringContentEntry("yarn.lock", content)
    )
  );

  t.is(commit, undefined);
  //t.is(await commit.entries[0].getString(), content);
});
